### ISSUE TITLE
These properties should be static final

### ISSUE THREAD

**Issue by Petorix** [chrisvanry/WeightLossContest#1]
Any class variables that are getting set and shouldn't be changed should be immutable (or any variables / properties in say a Globals file).  In C# this is known as a constant i.e. `private const string Email = "Admin";` 

I think in Java it's like this:
```
private static final String Email = "Admin";
private static final String Password = "12345678";

boolean static final isValid = false;
```

https://github.com/chrisvanry/WeightLossContest/blob/5ecee04ee00d30b7bde52027ab13d9d43826f7bd/app/src/main/java/com/chrisvanry/weightlosscontest/MainActivity.java#L19-L22

**Comment by Petorix** [comment]
It looks like `isValid` is set in the code, so that wouldn't be `static final`

**Comment by chrisvanry** [comment]
Fixed.
