### ISSUE TITLE
Remove unneeded variable creations and new function name recommendation

### ISSUE THREAD

**Issue by Petorix** [chrisvanry/WeightLossContest#2]
The variable `boolean isValid = false;` on line 22 isn't needed as the validation occurs only once.  In fact the variable on line 52 isn't required either `isValid = validate(inputEmail, inputPassword);`.  A better approach is to actually call that function in the if statement like so `if (!validate(inputEmail, inputPassword))`.

This next suggestion is more of a recommendation based off of best practices.  I recommend starting now with following best practices as it will look good for you when you start doing this professionally.  I think if you ever come back to this code in a year from now, or if another developer were to come look at it, some of the naming would be confusing and can be cleared up.  So the best practice is thus, **Be very specific with your naming**.  Try and be concise with the names as much as possible, but it's definitely better to err on the side of being too specific.

So I recommend changing the name of your validation function to something like `validate(String email, String password)` to `validateUserInput(String email, String password)`.  I was also confused with these variables:

```
eEmail = findViewById(R.id.etEmail); 
ePassword = findViewById(R.id.etPassword); 
eLogin = findViewById(R.id.btnLogin);
```

https://github.com/chrisvanry/WeightLossContest/blob/5ecee04ee00d30b7bde52027ab13d9d43826f7bd/app/src/main/java/com/chrisvanry/weightlosscontest/MainActivity.java#L22-L75

**Comment by chrisvanry** [comment]
Removed unnecessary variable and altered validation method. Renamed variables to be more specific.
