### ISSUE TITLE
Follow best practices where possible - followup

### ISSUE THREAD

**Issue by Petorix** [chrisvanry/WeightLossContest#3]
This is a recommendation and a follow up to my previous posted issue.

Follow Java coding best practices wherever possible.  I know you're still learning / practicing Java, but the sooner that best practices becomes muscle memory, the better for your future career as a developer will be.

I don't know Java at all, so I'm only trying to leave best practices that can be translated to any language, because of that, check out this site that is Java specific:

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

**Comment by chrisvanry** [comment]
Will do!
